### ISSUE TITLE
Unit Test TODO

### ISSUE THREAD

**Issue by mpowelson** [tesseract-robotics/tesseract#297]
- [x] tesseract_common: ltrim, rtrim, trim
- [ ] tesseract_common: QueryStringValue
- [ ] tesseract_common: QueryStringAttribute(Required)
- [ ] tesseract_common: QueryDoubleAttributeRequired
- [ ] ManipulatorManager::getGroupNames
- [ ] ManipulatorManager::getChainGroups
- [ ] ManipulatorManager::addLinkGroup
- [ ] ManipulatorManager::removeLinkGroup
- [ ] ManipulatorManager::removeROPKinematicsSolver
- [ ] ManipulatorManager::addREPKinematicsSolver
- [ ] ManipulatorManager::getGroupsJointState
- [ ] ManipulatorManager::addGroupTCP
- [ ] ManipulatorManager::getGroupsTCP
- [ ] ManipulatorManager::hasGroupTCP
- [ ] ManipulatorManager::getAvailableFwdKinematicsSolvers
- [ ] ManipulatorManager::removeFwdKinematicsFactory
- [ ] ManipulatorManager::getFwdKinematicFactory
- [ ] Environment::reset()
- [ ] Environment::applyCommands(const std::vector<Command>& commands)
- [ ] bool Environment::isInitialized()
- [ ] bool SceneGraph::addLink(Link link, Joint joint)
- [ ] bool SceneGraph::removeJoint(const std::string& name)
- [ ] bool SceneGraph::changeJointLimits(const std::string& name, const JointLimits& limits)
- [ ] Link::ConstPtr SceneGraph::getSourceLink(const std::string& joint_name)
- [ ] Link::ConstPtr SceneGraph::getTargetLink(const std::string& joint_name)
- [ ] std::vector<Joint::ConstPtr> SceneGraph::getInboundJoints(const std::string& link_name) 
- [ ] Add unit test for ompl problem generator
- [ ] Add unit test for trajopt problem generator
- [ ] Add unit test for descartes problem generator
- [ ] tesseract_command_language - This should be pretty easy to get close to 100% coverage

**Comment by mpowelson** [comment]
I went through and added some to the list looking at [CodeCov](https://codecov.io/gh/ros-industrial-consortium/tesseract) after the command language merge. Some of these should be pretty simple

**Comment by Levi-Armstrong** [comment]
These have been addressed with the exception of the command language which is no longer located in this repository.
